#!/bin/bash

planck --quiet --init=<(cat <<END

(require '[planck.core :refer [slurp]])
(require '[cljs.reader :refer [read-string]])

(def api (read-string (slurp "cljs-api.edn")))

(println)
(println "Explore the 'api' var.")
(println)

END) --repl
