(ns cljs-api-gen.config)

;; location of the clojure & clojurescript repos to parse
(def repo-dir "repos")

(def ^:dynamic *docs-repo-dir*)

(def docs-branch "docs")
(def examples-branch "examples")

(def edn-output-file "autodocs.edn")

(def docs-dir "docs")

(def history-filename "symbol-history")
(def changes-filename "changes")

;; location of the documents generated by this program
(def ^:dynamic *output-dir* nil)

(def ^:dynamic *repo-version*
  {"clojure" nil
   "clojurescript" nil})

