(ns cljs-api-gen.config)

(def default-out-dir "catalog")

;; location of manual cljsdoc files
(def cljsdoc-dir "cljsdoc")

;; cache directory
(def cache-dir ".api-cache")
(def edn-parsed-file "cljs-api-parsed.edn")
(def edn-cljsdoc-file "cljsdoc.edn")

;; location of the clojure & clojurescript repos to parse
(def repos-dir "repos")

(def edn-result-file "cljs-api.edn")
(def refs-dir "refs")

;; location of the documents generated by this program
(def ^:dynamic *output-dir* nil)

